"""Deterministic atlas packing geometry."""

from bellium.atlas.packing import (
    METHODS,
    NO_ROOM,
    OVERSIZED,
    AtlasPlan,
    Frame,
    Placement,
    Unplaced,
    cells,
    check_plan,
    pack,
    parse_frames,
    power_of_two_ceiling,
)
from bellium.atlas.png import (
    COLOR_TYPES,
    MAX_RAW_BYTES,
    PNG_SIGNATURE,
    PngInfo,
    decode_png,
    encode_pages,
    encode_png,
    inspect_png,
)
from bellium.atlas.dedup import (
    Alias,
    DedupReport,
    DuplicateGroup,
    analyze_frames,
    check_aliases,
    content_key,
    unique_frames,
)
from bellium.atlas.raster import (
    CHANNELS,
    DEFAULT_BACKGROUND,
    AtlasRaster,
    RasterPage,
    check_raster,
    check_sources,
    page_digest,
    pixel_problem,
    rasterize,
    source_shape,
)

__all__ = [
    "Alias",
    "CHANNELS",
    "COLOR_TYPES",
    "DEFAULT_BACKGROUND",
    "DedupReport",
    "DuplicateGroup",
    "MAX_RAW_BYTES",
    "METHODS",
    "NO_ROOM",
    "OVERSIZED",
    "AtlasPlan",
    "AtlasRaster",
    "Frame",
    "Placement",
    "PNG_SIGNATURE",
    "PngInfo",
    "RasterPage",
    "Unplaced",
    "analyze_frames",
    "cells",
    "check_plan",
    "check_aliases",
    "check_raster",
    "check_sources",
    "content_key",
    "decode_png",
    "encode_pages",
    "encode_png",
    "inspect_png",
    "pack",
    "page_digest",
    "parse_frames",
    "pixel_problem",
    "power_of_two_ceiling",
    "rasterize",
    "source_shape",
    "unique_frames",
]
